-- Migration 006: RBAC data layer — users + invites tables (Phase 1)
--
-- Phase 1 is DATA LAYER ONLY. These tables are NOT yet read by auth, sessions,
-- middleware, routes, or any frontend code. Wiring happens in later phases.
--
-- Role model (increasing privilege): viewer < editor < admin < super_admin.
-- The legacy "operator" role is intentionally NOT used here.
--
-- Requires PostgreSQL 13+ (gen_random_uuid() is built in; no extension needed).
-- Idempotent: IF NOT EXISTS / ON CONFLICT DO NOTHING. Run via: npm run db:migrate

BEGIN;

-- ============================================================
-- users — dashboard accounts (replaces .data/dashboard-users.json)
-- password_hash keeps the existing "scrypt:<salt>:<hex>" format produced by
-- src/lib/auth/passwords.ts. The migration copies hashes verbatim — never rehash.
-- email is stored lower-cased by all writers; UNIQUE enforces one account each.
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email          TEXT NOT NULL UNIQUE,
  password_hash  TEXT NOT NULL,
  role           TEXT NOT NULL DEFAULT 'viewer'
    CHECK (role IN ('viewer', 'editor', 'admin', 'super_admin')),
  active         BOOLEAN NOT NULL DEFAULT TRUE,
  display_name   TEXT,
  avatar_url     TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at  TIMESTAMPTZ
);

-- ============================================================
-- invites — pending account invitations (issued/consumed in a later phase)
-- token: unique unguessable string generated by the app.
-- created_by: the super_admin who issued the invite (NULL if that user is
-- later deleted).
-- ============================================================
CREATE TABLE IF NOT EXISTS invites (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email       TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT 'viewer'
    CHECK (role IN ('viewer', 'editor', 'admin', 'super_admin')),
  token       TEXT NOT NULL UNIQUE,
  expires_at  TIMESTAMPTZ NOT NULL,
  used_at     TIMESTAMPTZ,
  created_by  UUID REFERENCES users (id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invites_email_lower ON invites (LOWER(email));
CREATE INDEX IF NOT EXISTS idx_invites_pending
  ON invites (LOWER(email)) WHERE used_at IS NULL;

INSERT INTO schema_migrations (version, description)
VALUES ('006', 'RBAC data layer: users + invites tables (Phase 1)')
ON CONFLICT (version) DO NOTHING;

COMMIT;
